### ISSUE TITLE
About/Porfolio/Services Hashlink is not working

### ISSUE THREAD

**Issue by THENNARASU** [Osalumense/mld#3]
This is an excellent project to refer to.

I ran into an issue where i m not able to get the hashlink for "div" elements working.

Is there a fix for this?

It appears that there is some functionality break with react hashlink router dom since react 6.

**Comment by THENNARASU** [comment]
Strangely, the links work when they are double clicked. Also, i see some of the sections top portion is hidden.

**Comment by ishaiktaher** [comment]
@THENNARASU  Let me know if you were able to resolve this!!

**Comment by THENNARASU** [comment]
Hi, I m available now. Do you want to connect now? If it is okay with you, can you share the meeting invite?

**Comment by ishaiktaher** [comment]
@THENNARASU Can you pls suggest the solution here, Will try and can connect if it still fails

**Comment by ishaiktaher** [comment]
Am able to resolve this issue by adding below condition in useEffect of `ScrollToTop.js`

`      if(location.pathname !== "/")
`

**Comment by THENNARASU** [comment]
Wow. It works!! One other help though, when the link does scroll down but it is not showing the header of the section, or in some cases it is partial.

**Comment by Osalumense** [comment]
This has been fixed. Thanks to @lavonhf you can pull from the main branch and also review the changes made.
I would be closing this now. Thank you
